from __future__ import annotations

import json
import os
import re
from typing import Any
from uuid import uuid4

import httpx2

from openai import (
    APIConnectionError,
    APIStatusError,
    APITimeoutError,
    OpenAI,
)

from boilermind.core.contracts import (
    ResearchProblemSpec,
)
from boilermind.hypothesis.deterministic_admission import required_objective_dimensions
from boilermind.orchestration.target_normalizer import normalize_target_variable


class QwenProblemParserError(
    RuntimeError
):
    pass


class QwenProblemParser:
    """
    Convert a user-supplied natural-language scientific
    question into a trusted ResearchProblemSpec.

    The parser MUST NOT hard-code a specific research
    target, operating condition, or variable set.

    problem_id is generated by the system.
    original_question is bound by the system.
    Qwen only structures the scientific semantics.
    """

    _SCALAR_FIELDS = {
        "research_object",
        "target_variable",
        "objective",
        "operating_condition",
        "research_goal",
    }

    _LIST_FIELDS = {
        "manipulated_variables",
        "observed_variables",
        "context_variables",
        "success_criteria",
        "constraints",
        "metrics",
    }

    _EXPECTED_FIELDS = (
        _SCALAR_FIELDS
        | _LIST_FIELDS
    )

    def __init__(
        self,
        *,
        api_key: str | None = None,
        base_url: str | None = None,
        model: str | None = None,
        timeout: float = 90.0,
        client: Any | None = None,
    ):
        self.model = (
            model
            or os.getenv(
                "BOILERMIND_QWEN_MODEL",
                "qwen3.7-plus",
            )
        )

        self.timeout = timeout
        self._owns_client = False

        #
        # Dependency injection for unit tests.
        #
        if client is not None:
            self._client = client
            return

        api_key = (
            api_key
            or os.getenv(
                "DASHSCOPE_API_KEY"
            )
        )

        base_url = (
            base_url
            or os.getenv(
                "BOILERMIND_QWEN_BASE_URL"
            )
        )

        if not api_key:
            raise QwenProblemParserError(
                "DASHSCOPE_API_KEY "
                "is not configured."
            )

        if not base_url:
            raise QwenProblemParserError(
                "BOILERMIND_QWEN_BASE_URL "
                "is not configured."
            )

        #
        # The current deployment has verified that
        # direct HTTP routing is required.
        #
        trust_env = os.getenv(
            "BOILERMIND_QWEN_TRUST_ENV",
            "false",
        ).strip().lower() in {
            "1",
            "true",
            "yes",
            "on",
        }
        http_client = httpx2.Client(
            trust_env=trust_env,
            timeout=self.timeout,
        )

        self._client = OpenAI(
            api_key=api_key,
            base_url=base_url,
            http_client=http_client,
            timeout=self.timeout,
            max_retries=0,
        )

        self._owns_client = True

    @staticmethod
    def _system_prompt() -> str:
        return """
You are the Research Problem Parser in a trusted
AI Scientist system for industrial boiler research.

Your task is STRUCTURING, not solving the research
problem.

Convert the CURRENT user question into a structured
scientific problem description.

Important rules:

1. Never replace the current question with a predefined
   boiler research problem.

2. Never assume the target is steam flow, NOx, drum
   level, efficiency, or any other variable unless the
   current user question implies or states it.

3. Never invent exact operating ranges, thresholds,
   sampling intervals, model names, sensor names, or
   numerical targets that are not present in the input.

4. The fields research_object, target_variable, objective,
   operating_condition and research_goal MUST each be
   one JSON string, never an array.

   For multi-objective questions, target_variable should
   preserve the primary prediction/control target and
   secondary objectives should be represented through
   observed_variables, context_variables,
   success_criteria, and constraints.

   If a scalar concept is genuinely unspecified, use
   the string "unspecified".

   target_variable is the physical or engineering quantity
   predicted by the model. Phrases such as prediction accuracy,
   accuracy improvement, lower error, MAE, RMSE, and R2 are NOT
   target variables. Put the scientific evaluation aim in
   objective and the metric names in metrics.

   Horizon labels such as h40, h80, horizon=80 and
   "80步预测" are prediction horizons, NOT target variables.
   In this BoilerMind vocabulary, "直接V" / "direct-V"
   denotes direct steam volumetric-flow prediction.

5. If a variable category is unspecified, use an empty
   list.

6. manipulated_variables means variables that may be
   actively adjusted or experimentally intervened on.

7. observed_variables means measured variables directly
   relevant to answering the question.

8. context_variables means operating-state, disturbance,
   environmental, temporal, or other conditioning
   variables.

9. success_criteria must describe what evidence would
   make the research question answerable or testable.
   Do not invent numerical thresholds.

10. research_goal should be a concise scientific
    reformulation of the user's actual question, not a
    proposed answer.

All of the following fields MUST be JSON arrays of
strings, even when there is only one item:

- manipulated_variables
- observed_variables
- context_variables
- success_criteria
- constraints
- metrics

Never return a single string for these fields.

Return JSON only.

Required JSON fields:

research_object
target_variable
objective
operating_condition
manipulated_variables
observed_variables
context_variables
research_goal
success_criteria
constraints
metrics
""".strip()

    @staticmethod
    def _separate_target_and_objective(
        payload: dict,
        question: str,
    ) -> None:
        """Prevent evaluation language from becoming a prediction target."""
        question_text = question.casefold()
        target_text = str(payload.get("target_variable", "")).casefold()
        evaluation_terms = (
            "预测精度", "准确率提升", "提高准确率", "误差降低",
            "降低误差", "prediction accuracy", "accuracy improvement",
            "lower error", "mae", "rmse", "r2",
        )
        target_is_evaluation = any(term in target_text for term in evaluation_terms)
        asks_accuracy = any(term in question_text for term in evaluation_terms)

        if target_is_evaluation:
            payload["target_variable"] = "unspecified"

        target_is_horizon = bool(
            re.fullmatch(r"h(?:orizon)?\s*[=:]?\s*\d+", target_text)
        )
        direct_volume_terms = (
            "直接v", "direct-v", "direct v", "主蒸汽体积流量",
            "直接蒸汽体积流量",
            "steam volumetric flow",
        )
        canonical_direct_volume_targets = {
            "steam volumetric flow",
            "steam_volumetric_flow",
            "main steam volumetric flow",
            "主蒸汽体积流量",
            "直接蒸汽体积流量",
        }
        target_tokens = set(re.findall(r"[a-z]+", target_text))
        is_descriptive_steam_volume_target = {
            "steam", "volumetric", "flow"
        }.issubset(target_tokens)
        if (
            target_text in canonical_direct_volume_targets
            or is_descriptive_steam_volume_target
        ):
            payload["target_variable"] = "steam_volumetric_flow"
        canonical_mass_flow_targets = {
            "main_steam_mass_flow",
            "main steam mass flow",
            "steam flow",
            "main steam flow",
            "主蒸汽质量流量",
            "主蒸汽流量",
            "蒸汽质量流量",
            "蒸汽流量",
            "蒸汽量",
        }
        is_descriptive_mass_flow_target = (
            {"main", "steam", "flow"}.issubset(target_tokens)
            and "volumetric" not in target_tokens
        )
        contains_chinese_mass_flow_target = any(
            term in target_text
            for term in ("主蒸汽质量流量", "主蒸汽流量", "蒸汽质量流量")
        )
        if (
            target_text in canonical_mass_flow_targets
            or is_descriptive_mass_flow_target
            or contains_chinese_mass_flow_target
        ):
            payload["target_variable"] = "main_steam_mass_flow"
        if target_is_horizon:
            if any(term in question_text for term in direct_volume_terms):
                payload["target_variable"] = "steam_volumetric_flow"
                payload["target_inference_reason"] = (
                    "direct_volume_task_alias_resolved;"
                    "horizon_label_removed_from_target"
                )
            else:
                payload["target_variable"] = "unspecified"
                payload["target_inference_reason"] = (
                    "horizon_label_is_not_a_physical_target"
                )

        if asks_accuracy:
            payload["objective"] = "improve_prediction_accuracy"
            payload["metrics"] = ["MAE", "RMSE", "R2"]

    @staticmethod
    def _execution_constraints(question: str) -> dict:
        """Extract user-declared protocol constraints without LLM inference."""
        text = question.casefold()
        model_patterns = (
            ("persistence", r"\bpersistence\b|持久性(?:基线)?"),
            ("bayesianridge", r"\bbayesian\s*ridge\b|\bbayesianridge\b|贝叶斯岭"),
            ("ridge", r"(?<!bayesian)\bridge\b|(?<!贝叶斯)岭回归"),
            ("rf", r"\brandom\s*forest\b|\brf\b|随机森林"),
            ("lstm", r"(?<![a-z0-9_])lstm(?![a-z0-9_])"),
            ("transformer", r"(?<![a-z0-9_])transformer(?![a-z0-9_])"),
        )
        models = [name for name, pattern in model_patterns if re.search(pattern, text)]
        references = [name for name in models if name == "persistence"]
        candidates = [name for name in models if name not in references]

        horizon = None
        explicit = re.search(r"(?<![a-z0-9_])h\s*(80|40|20|8|4)(?![0-9])", text)
        if explicit:
            horizon = int(explicit.group(1))
        else:
            minute_match = re.search(r"(20|10|5|2|1)\s*分钟", text)
            if minute_match:
                horizon = {"20": 80, "10": 40, "5": 20, "2": 8, "1": 4}[
                    minute_match.group(1)
                ]

        operations = []
        protocol = []
        if len(models) >= 2 or any(token in text for token in ("比较", "对比", "compare")):
            operations.append("model_comparison")
        if "validation" in text or "验证集" in text:
            operations.append("chronological_validation")
            protocol.append("validation_only_model_selection")
        if "locked-test" in text or "locked_test" in text or "锁定测试" in text:
            operations.append("locked_test_evaluation")
            protocol.append("locked_test_not_used_for_selection")

        return {
            "required_models": candidates,
            "reference_models": references,
            "required_horizon_steps": horizon,
            "required_operations": list(dict.fromkeys(operations)),
            "protocol_constraints": list(dict.fromkeys(protocol)),
        }

    @staticmethod
    def _parse_json_content(
        content: str,
    ) -> dict:
        text = content.strip()

        if text.startswith("```"):
            lines = text.splitlines()

            if lines:
                lines = lines[1:]

            if (
                lines
                and lines[-1]
                .strip()
                .startswith("```")
            ):
                lines = lines[:-1]

            text = "\n".join(
                lines
            ).strip()

        parsed = json.loads(text)

        if not isinstance(
            parsed,
            dict,
        ):
            raise ValueError(
                "Qwen problem output "
                "must be a JSON object."
            )

        return parsed

    @classmethod
    def _validate_payload(
        cls,
        payload: dict,
    ) -> None:
        returned = set(
            payload
        )

        missing = (
            cls._EXPECTED_FIELDS
            - returned
        )

        unexpected = (
            returned
            - cls._EXPECTED_FIELDS
        )

        if missing or unexpected:
            raise QwenProblemParserError(
                "Qwen problem structure does not "
                "match the required contract. "
                f"Missing={missing}; "
                f"Unexpected={unexpected}"
            )

        for field in cls._SCALAR_FIELDS:
            value = payload[field]

            #
            # Multi-objective scientific questions may
            # cause an LLM to return several closely
            # related concepts for a scalar contract
            # field. Preserve the information by
            # canonicalizing a list of strings into one
            # structured string.
            #
            if isinstance(
                value,
                list,
            ):
                normalized_items = [
                    item.strip()
                    for item in value
                    if (
                        isinstance(
                            item,
                            str,
                        )
                        and item.strip()
                    )
                ]

                value = "; ".join(
                    normalized_items
                )

                payload[field] = value

            elif value is None:
                value = "unspecified"
                payload[field] = value

            elif isinstance(
                value,
                str,
            ):
                value = value.strip()

                if not value:
                    value = "unspecified"

                payload[field] = value

            else:
                raise QwenProblemParserError(
                    f"{field} must be a "
                    "string or list of strings."
                )

        for field in cls._LIST_FIELDS:
            value = payload[field]

            #
            # LLM normalization boundary:
            #
            # A single scientifically valid string is
            # normalized into a one-item list before the
            # strict ResearchProblemSpec contract.
            #
            # Other unexpected types still fail closed.
            #
            if isinstance(
                value,
                str,
            ):
                normalized = (
                    value.strip()
                )

                payload[field] = (
                    [normalized]
                    if normalized
                    else []
                )

                value = payload[field]

            if not isinstance(
                value,
                list,
            ):
                raise QwenProblemParserError(
                    f"{field} must be a list."
                )

            normalized_items = []

            for item in value:
                if (
                    not isinstance(
                        item,
                        str,
                    )
                    or not item.strip()
                ):
                    raise QwenProblemParserError(
                        f"{field} contains an "
                        "invalid item."
                    )

                normalized_items.append(
                    item.strip()
                )

            payload[field] = (
                normalized_items
            )

    def parse(
        self,
        question: str,
        *,
        problem_id: str | None = None,
    ) -> ResearchProblemSpec:
        if (
            not isinstance(
                question,
                str,
            )
            or not question.strip()
        ):
            raise QwenProblemParserError(
                "Research question "
                "must not be empty."
            )

        try:
            completion = (
                self._client
                .chat
                .completions
                .create(
                    model=self.model,
                    messages=[
                        {
                            "role": "system",
                            "content": (
                                self._system_prompt()
                            ),
                        },
                        {
                            "role": "user",
                            "content": (
                                "CURRENT research "
                                "question:\n"
                                + question
                            ),
                        },
                    ],
                    response_format={
                        "type": "json_object"
                    },
                    temperature=0.0,
                    extra_body={
                        "enable_thinking": False,
                    },
                )
            )

        except APITimeoutError as exc:
            raise QwenProblemParserError(
                "Qwen problem parsing "
                "request timed out."
            ) from exc

        except APIConnectionError as exc:
            raise QwenProblemParserError(
                "Qwen problem parsing "
                f"connection failed: {exc}"
            ) from exc

        except APIStatusError as exc:
            raise QwenProblemParserError(
                "Qwen problem parsing "
                "returned HTTP "
                f"{exc.status_code}."
            ) from exc

        except Exception as exc:
            raise QwenProblemParserError(
                "Qwen problem parsing "
                f"request failed: {exc}"
            ) from exc

        try:
            content = (
                completion
                .choices[0]
                .message
                .content
            )

            if not content:
                raise ValueError(
                    "Empty Qwen response."
                )

            payload = (
                self._parse_json_content(
                    content
                )
            )

        except Exception as exc:
            if isinstance(
                exc,
                QwenProblemParserError,
            ):
                raise

            raise QwenProblemParserError(
                "Qwen returned invalid "
                "problem-structure JSON."
            ) from exc

        self._validate_payload(payload)
        raw_target_variable = payload["target_variable"]
        self._separate_target_and_objective(payload, question)
        target_normalization = normalize_target_variable(
            raw_target_variable,
            question,
        )
        payload["target_variable"] = (
            target_normalization.normalized_target_variable
        )

        assigned_problem_id = (
            problem_id
            or (
                "RP-"
                + uuid4()
                .hex[:12]
                .upper()
            )
        )

        execution_constraints = self._execution_constraints(question)
        execution_constraints["required_objective_dimensions"] = (
            required_objective_dimensions(question)
        )

        return ResearchProblemSpec(
            problem_id=assigned_problem_id,

            #
            # Bound directly to user input.
            # Qwen may not replace it.
            #
            original_question=question,

            research_object=(
                payload[
                    "research_object"
                ]
            ),
            target_variable=(
                payload[
                    "target_variable"
                ]
            ),
            raw_target_variable=target_normalization.raw_target_variable,
            normalized_target_variable=(
                target_normalization.normalized_target_variable
            ),
            target_normalization_reason=(
                target_normalization.normalization_reason
            ),
            objective=payload["objective"],
            metrics=payload["metrics"],
            target_inference_reason=(
                str(payload.get("target_inference_reason") or "")
                or target_normalization.normalization_reason
            ),
            **execution_constraints,
            operating_condition=(
                payload[
                    "operating_condition"
                ]
            ),
            manipulated_variables=(
                payload[
                    "manipulated_variables"
                ]
            ),
            observed_variables=(
                payload[
                    "observed_variables"
                ]
            ),
            context_variables=(
                payload[
                    "context_variables"
                ]
            ),
            research_goal=(
                payload[
                    "research_goal"
                ]
            ),
            success_criteria=(
                payload[
                    "success_criteria"
                ]
            ),
            constraints=(
                payload[
                    "constraints"
                ]
            ),
        )

    def close(self) -> None:
        if self._owns_client:
            self._client.close()
